function DataManager_control_button(hf, pos, varargin)
%%add control buttons to spike dabase viewer
%%three major groups: (1) view and output selected spike/field values

%%hf = main figure to put control puttons on
%%pos = [left bottom width height] for the entire control area: unit = normalized now in respect to figure dimension

%%%%%%added varargin for more options to make it universal for different types of databases
dbtype = getappdata(hf, 'dbtype');
nopvar = size(varargin, 2);
if (nopvar == 1)
    dbtype = varargin{1};
%elseif (nopvar == 2)
    %dbtype = varargin{1}; plotparm = varargin{2};
%elseif (nopvar == 3)
%    celllisttitle = varargin{1}; celllistvar = varargin{2}; dbtype = varargin{3};    
end

%%%%%%%inherit plot parameters
if (isappdata(hf, 'plotparm'))
    plotparm = getappdata(hf, 'plotparm');
else
    plotparm.bin = 1; plotparm.range = [0 10]; plotparm.setlog = 0;
    plotparm.showdetail = 1; plotparm.compute = 0; plotparm.overwrite = 0; plotparm.evselect = 0;
    if strcmp(dbtype, '.spikedb')
       plotparm.linkspike = 1; plotparm.linkeeg = 0; plotparm.linkbehav = 0;
    elseif strcmp(dbtype, '.eegdb')
       plotparm.linkspike = 0; plotparm.linkeeg = 1; plotparm.linkbehav = 0;
    elseif strcmp(dbtype, '.behavdb')
       plotparm.linkspike = 0; plotparm.linkeeg = 0; plotparm.linkbehav = 1;
    elseif strcmp(dbtype, '.seqdb')
       plotparm.linkspike = 0; plotparm.linkeeg = 0; plotparm.linkbehav = 0;
       %plotparm.shufflemode = 'GlobalID'; plotparm.shuffletimes = 1000; plotparm.significancelevel = 0.05;
    else
       plotparm.linkspike = 0; plotparm.linkeeg = 0; plotparm.linkbehav = 0;
    end
    setappdata(hf, 'plotparm', plotparm);%default plot parameters
end

Hgap = 0.003; Vgap = 0.003; Bwidth = (pos(3)-8*Hgap)/2; Bheight = (pos(4)/7 - 8*Vgap)/5; 
fheight = (pos(4)-8*Vgap)/7;
%big frame to cover the whole right field
uicontrol('Style', 'frame', 'Parent', hf, 'BackgroundColor', [0.8 0.8 0.8], 'Units', 'normalized', 'Position', pos);

%upper frame: spike selection/output
pp = [pos(1)+Hgap pos(2)+7*Vgap+6*fheight pos(3)-2*Hgap fheight]; uicontrol('Style', 'frame', 'Parent', hf, 'BackgroundColor', [0.8 0.8 0.8], 'Units', 'normalized', 'Position', pp);
%spike selection buttons
ppo = [pp(1)+Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Update',...
    'Units', 'normalized', 'Tag', 'updatevalue', 'Position', ppo, 'Callback', 'DataManager_UpdateDisplay_Callback');
%ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String',...
%    'SaveGroup', 'Units', 'normalized', 'Tag', 'savegroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String',...
    'OutputEvts', 'Units', 'normalized', 'Tag', 'outputevents', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');

ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String',...
    'ShowCrit', 'Units', 'normalized', 'Tag', 'showcrit', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+0.5*Bwidth+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Del', 'Units', 'normalized', 'Tag', 'deletegroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+2.5*Hgap+Bwidth  pp(2)+pp(4)-2*Vgap-2*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String',...
    'Redo1', 'Units', 'normalized', 'Tag', 'redoone', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+1.5*Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'RedoAll', 'Units', 'normalized', 'Tag', 'redoall', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');

ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'AutoSel', 'Units', 'normalized',...
    'Tag', 'autoselect', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+0.5*Bwidth+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String',...
    'ManuSel', 'Units', 'normalized', 'Tag', 'manuselect', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+2.5*Hgap+Bwidth  pp(2)+pp(4)-3*Vgap-3*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Export', 'Units', 'normalized',...
    'Tag', 'savegroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+1.5*Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight 0.5*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String',...
    'Import', 'Units', 'normalized', 'Tag', 'importgroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');

ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'SelectAll', 'Units', 'normalized',...
    'Tag', 'spikeselectall', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'DeSelectAll', 'Units', 'normalized',...
    'Tag', 'spikeselectallnot', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');

ppo = [pp(1)+Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/3 Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', '++', 'Units', 'normalized',...
    'Tag', 'combinegroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+Bwidth/3+2*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/3 Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', '--', 'Units', 'normalized',...
    'Tag', 'subtractgroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+2*Bwidth/3+3*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/3 Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'nn', 'Units', 'normalized',...
    'Tag', 'intersectgroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+Bwidth+4*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/3 Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', '/n', 'Units', 'normalized',...
    'Tag', 'reverseintgroup', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');
ppo = [pp(1)+Bwidth*4/3+5*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth*2/3 Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'RandDown', 'Units', 'normalized',...
    'Tag', 'downsamplegroups', 'Position', ppo, 'Callback', 'DataManager_SpikeSelect_Callback');

%%second frmae: plot data
pp = [pos(1)+Hgap pos(2)+5*Vgap+5*fheight pos(3)-2*Hgap fheight];
uicontrol('Style', 'frame', 'Parent', hf, 'BackgroundColor', [0.8 0.8 0.8], 'Units', 'normalized', 'Position', pp);
%%%%%generate plots
ppo = [pp(1)+Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Hist',...
    'Units', 'normalized', 'Tag', 'hist', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Polar', 'Units', 'normalized',...
    'Tag', 'polar', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Cumu', 'Units', 'normalized',...
    'Tag', 'cumu', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Bar', 'Units', 'normalized',...
    'Tag', 'bar', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Regression', 'Units', 'normalized',...
    'Tag', 'regression', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Scatter', 'Units', 'normalized',...
    'Tag', 'scatter', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Function', 'Units', 'normalized',...
    'Tag', 'function', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');

%%%%plot parameters
%plotparm.bin = 1; plotparm.range = [0 10]; plotparm.setlog = 0;
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; ppt = uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Linear', 'Units', 'normalized', 'Tag', 'setlog', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/2 Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
    'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'Range',...
    'Units', 'normalized', 'Tag', 'rangestatic', 'Position',ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+Hgap+Bwidth/2  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/2+6*Hgap Bheight-Vgap]; uicontrol('Style', 'edit', 'Parent', hf,...
    'ForegroundColor', [1 0 0], 'String', num2str(plotparm.range),...
    'Units', 'normalized', 'Tag', 'setrange', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+3*Hgap+Bwidth+2*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/2-2*Hgap Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
    'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'Bin',...
    'Units', 'normalized', 'Tag', 'binstatic', 'Position',ppo, 'Callback', 'DataManager_plot_Callback');
ppo = [pp(1)+3*Hgap+Bwidth+Bwidth/2  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth/2 Bheight-Vgap]; uicontrol('Style', 'edit', 'Parent', hf,...
    'ForegroundColor', [1 0 0], 'String', num2str(plotparm.bin),...
    'Units', 'normalized', 'Tag', 'setbin', 'Position', ppo, 'Callback', 'DataManager_plot_Callback');

%%3rd frmae: statistics
pp = [pos(1)+Hgap pos(2)+3*Vgap+3.42*fheight pos(3)-2*Hgap 1.6*fheight];
uicontrol('Style', 'frame', 'Parent', hf, 'BackgroundColor', [0.8 0.8 0.8], 'Units', 'normalized', 'Position', pp);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'Ttest',...
    'Units', 'normalized', 'Tag', 'ttest', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'ranksum',...
    'Units', 'normalized', 'Tag', 'ranksum', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'pairedT',...
    'Units', 'normalized', 'Tag', 'pairedt', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'signtest', 'Units', 'normalized', 'Tag', 'signtest', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'ANOVA1',...
    'Units', 'normalized', 'Tag', 'anova1', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'KWtest', 'Units', 'normalized', 'Tag', 'kwtest', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'ANOVA2',...
    'Units', 'normalized', 'Tag', 'anova2', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; %uicontrol('Style', 'pushbutton', 'Parent', hf,...
    %'String', 'KStest', 'Units', 'normalized', 'Tag', 'kstest', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'KStest',...
    'Units', 'normalized', 'Tag', 'kstest', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf, 'String', 'WWtest',...
    'Units', 'normalized', 'Tag', 'wwtest', 'Position', ppo, 'Callback', 'DataManager_stattest_Callback');
%%%%still need to add: ftest, binomial, angletest
%%%no fridman test because it tests column effect after removing the row effect (incase not enough samples from one uniform condition);
%%%no Ztest because it requires a known std and ttest is good enough for the test with an unknown std
%%%no chi-square because it is a variance test, which is rarely used here (test if samples are from a normal distibution with a known variance
%%%no binomial test (given p and N, compute the probability of M): individual case, hard to implement with the data structure.


%%4-th frmae: manipulate the databasae
pp = [pos(1)+Hgap pos(2)+3*Vgap+2.4*fheight pos(3)-2*Hgap 0.98*fheight];
uicontrol('Style', 'frame', 'Parent', hf, 'BackgroundColor', [0.8 0.8 0.8], 'Units', 'normalized', 'Position', pp);
%%%%%change parms, remove spike/field buttons
ppo = [pp(1)+Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'RemveCells', 'Units', 'normalized', 'Tag', 'removecells', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'RemveVars', 'Units', 'normalized', 'Tag', 'removevars', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'SquzVals', 'Units', 'normalized', 'Tag', 'squeezevals', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'CopyVars', 'Units', 'normalized', 'Tag', 'copyvars', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'CrossSquz', 'Units', 'normalized', 'Tag', 'crosssqueezevals', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'RenamVars', 'Units', 'normalized', 'Tag', 'renamevars', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
     'String', 'ReassgnVals', 'Units', 'normalized', 'Tag', 'reassignvals', 'Position', ppo, ...
     'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Bwidth+3*Hgap pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
     'String', 'CreateVars', 'Units', 'normalized', 'Tag', 'createNewVar', 'Position', ppo, ...
     'Callback', 'DataManager_ManipulateValVar_Callback');
ppo = [pp(1)+Hgap pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ImportVars', 'Units', 'normalized', 'Tag', 'importVars', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback'); 
ppo = [pp(1)+Bwidth+3*Hgap pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ExportVars', 'Units', 'normalized', 'Tag', 'exportVars', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');

%%5-th frmae: add or re-compute specific variables (fields)
pp = [pos(1)+Hgap pos(2)+Vgap pos(3)-2*Hgap 2.4*fheight];
uicontrol('Style', 'frame', 'Parent', hf, 'BackgroundColor', [0.8 0.8 0.8], 'Units', 'normalized', 'Position', pp);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ChangeParm', 'Units', 'normalized', 'Tag', 'changeparm', 'Position', ppo, ...
    'Callback', 'DataManager_ManipulateValVar_Callback');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%From here below is specific for each dbtype%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch dbtype
    case '.spikedb'
        plotspikedbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth);
    case '.eegdb'
        ploteegdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth);
    case '.behavdb'
        plotbehavdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth);
    case '.crrdb'
        plotcrrdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth);
    case '.syncdb'
        plotsyncdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth);
    case '.seqdb'
        plotseqdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth, plotparm);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%control parameters for the analysis
bottom = pp(2)+pp(4)-12.35*Vgap-12.35*Bheight; Tgap = Bheight;
ppo = [pp(1)+Hgap bottom+3*Tgap Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Session', 'Units', 'normalized', 'Tag', 'setev', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); 
     if (plotparm.evselect == 0) 
         set(ppt, 'ForeGroundColor', [0.2 0.2 0.2], 'String', 'Session');
     else
         set(ppt, 'ForeGroundColor', [1 0 0], 'String', 'Events');
     end
     if (strcmp(dbtype, '.spikedb')) set(ppt, 'Style', 'text'); end
ppo = [pp(1)+Hgap bottom+2*Tgap Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'SpikeLinked', 'Units', 'normalized', 'Tag', 'linkspike', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); 
     if (plotparm.linkspike == 1) 
         set(ppt, 'ForeGroundColor', [1 0 0], 'String', 'SpikeLinked');
     else
         set(ppt, 'ForeGroundColor', [0.2 0.2 0.2], 'String', 'NoSpikeDB');
     end
     if (strcmp(dbtype, '.spikedb')) set(ppt, 'Style', 'text'); end
ppo = [pp(1)+Bwidth+3*Hgap bottom+2*Tgap Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'NoEEGDB', 'Units', 'normalized', 'Tag', 'linkeeg', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); 
     if (plotparm.linkeeg == 1) 
         set(ppt, 'ForeGroundColor', [1 0 0], 'String', 'EEGLinked');
     else
         set(ppt, 'ForeGroundColor', [0.2 0.2 0.2], 'String', 'NoEEGDB');
     end
     if (strcmp(dbtype, '.eegdb')) set(ppt, 'Style', 'text'); end
ppo = [pp(1)+Hgap bottom+Tgap Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'NoShow', 'Units', 'normalized', 'Tag', 'showdetail', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); 
     if (plotparm.showdetail == 1) 
         set(ppt, 'ForeGroundColor', [1 0 0], 'String', 'Show');
     else
         set(ppt, 'ForeGroundColor', [0.2 0.2 0.2], 'String', 'NoShow');
     end
ppo = [pp(1)+Bwidth+3*Hgap bottom+Tgap Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'NoBehavdb', 'Units', 'normalized', 'Tag', 'linkbehav', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); 
     if (plotparm.linkbehav == 1) 
         set(ppt, 'ForeGroundColor', [1 0 0], 'String', 'BehavLinked');
     else
         set(ppt, 'ForeGroundColor', [0.2 0.2 0.2], 'String', 'NoBehavDB');
     end
     if (strcmp(dbtype, '.behavdb')) set(ppt, 'Style', 'text'); end
ppo = [pp(1)+Hgap  bottom Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'NewDatabs', 'Units', 'normalized', 'Tag', 'overwrite', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); 
     if (plotparm.overwrite == 1) 
         set(ppt, 'ForeGroundColor', [1 0 0], 'String', 'Overwrite');
     else
         set(ppt, 'ForeGroundColor', [0.2 0.2 0.2], 'String', 'NewDB');
     end
ppo = [pp(1)+Bwidth+3*Hgap  bottom Bwidth Bheight]; ppt = uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'AssignParm', 'Units', 'normalized', 'Tag', 'assignparm', 'Position', ppo, ...
    'Callback', 'DataManager_plot_Callback'); 
     if (plotparm.compute == 1) 
         set(ppt, 'ForeGroundColor', [1 0 0], 'String', 'Compute');
     else
         set(ppt, 'ForeGroundColor', [0.2 0.2 0.2], 'String', 'AssignParm');
     end

function plotspikedbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth)
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptInit', 'Units', 'normalized', 'Tag', 'recomputeinit', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptAll', 'Units', 'normalized', 'Tag', 'recomputeall', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Firing', 'Units', 'normalized', 'Tag', 'firing', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Waveform', 'Units', 'normalized', 'Tag', 'waveform', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'CelLType', 'Units', 'normalized', 'Tag', 'celltype', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ClusterQua', 'Units', 'normalized', 'Tag', 'clusterqua', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Place Field', 'Units', 'normalized', 'Tag', 'pfprop', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'PFDynam', 'Units', 'normalized', 'Tag', 'pfdynam', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-6*Vgap-6*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Time Field', 'Units', 'normalized', 'Tag', 'timefield', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-6*Vgap-6*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ThetaPhase', 'Units', 'normalized', 'Tag', 'thetaphase', 'Position', ppo, ...
    'Callback', 'DataManager_ReCompute_Callback');
%%%%additonal plots to show hidden bhdata 
ppo = [pp(1)+Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'show1DPF', 'Units', 'normalized', 'Tag', 'show1dfields', 'Position', ppo, ...
    'Callback', 'DataManager_ShowPFdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'show2DPF', 'Units', 'normalized', 'Tag', 'show2dfields', 'Position', ppo, ...
    'Callback', 'DataManager_ShowPFdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
%%%%additonal plots to show hidden bhdata 
ppo = [pp(1)+Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'show1DPhase', 'Units', 'normalized', 'Tag', 'show1dphases', 'Position', ppo, ...
    'Callback', 'DataManager_ShowPFdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'show1DEnsemble', 'Units', 'normalized', 'Tag', 'show1densemble', 'Position', ppo, ...
    'Callback', 'DataManager_ShowPFdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);

function ploteegdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth)
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptInit', 'Units', 'normalized', 'Tag', 'recomputeinit', 'Position', ppo, ...
    'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptAll', 'Units', 'normalized', 'Tag', 'recomputeall', 'Position', ppo, ...
    'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'SlowTheta', 'Units', 'normalized', 'Tag', 'slowtheta', 'Position', ppo, ...
    'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Spectral', 'Units', 'normalized', 'Tag', 'spectral', 'Position', ppo, ...
    'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Ripples', 'Units', 'normalized', 'Tag', 'ripples', 'Position', ppo, ...
    'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Theta', 'Units', 'normalized', 'Tag', 'theta', 'Position', ppo, ...
    'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
     'String', 'Spindle', 'Units', 'normalized', 'Tag', 'spindle', 'Position', ppo, ...
     'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
     'String', 'HVS', 'Units', 'normalized', 'Tag', 'hvs', 'Position', ppo, ...
     'Callback', 'DataManager_EEGReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
     'String', 'Cluster0', 'Units', 'normalized', 'Tag', 'cluster0', 'Position', ppo, ...
     'Callback', 'DataManager_EEGReCompute_Callback');
%%%%additonal plots to show hidden eegdata 
ppo = [pp(1)+Hgap  pp(2)+pp(4)-6.35*Vgap-6.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'showEEG', 'Units', 'normalized', 'Tag', 'showeegdata', 'Position', ppo, ...
    'Callback', 'DataManager_EEGShowEEGdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-6.35*Vgap-6.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'SigDist', 'Units', 'normalized', 'Tag', 'signaldist', 'Position', ppo, ...
    'Callback', 'DataManager_EEGShowEEGdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'CrossCrr', 'Units', 'normalized', 'Tag', 'crosscorrelation', 'Position', ppo, ...
    'Callback', 'DataManager_EEGShowEEGdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+2*Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth/2 Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'TrigAvg', 'Units', 'normalized', 'Tag', 'triggeraverage', 'Position', ppo, ...
    'Callback', 'DataManager_EEGShowEEGdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap+Bwidth/2  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth/2+2*Hgap Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'TrigIncidnce', 'Units', 'normalized', 'Tag', 'triggerincidence', 'Position', ppo, ...
    'Callback', 'DataManager_EEGShowEEGdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Spectrogram', 'Units', 'normalized', 'Tag', 'spectrogram', 'Position', ppo, ...
    'Callback', 'DataManager_EEGShowEEGdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'PSD', 'Units', 'normalized', 'Tag', 'PSD', 'Position', ppo, ...
    'Callback', 'DataManager_EEGShowEEGdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);

function plotbehavdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth)
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-Vgap-Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'AddTrajDistance', 'Units', 'normalized', 'Tag', 'trajdistance', 'Position', ppo, ...
    'Callback', 'DataManager_BehavAddTrajDistance_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptInit', 'Units', 'normalized', 'Tag', 'recomputeinit', 'Position', ppo, ...
    'Callback', 'DataManager_BehavReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptAll', 'Units', 'normalized', 'Tag', 'recomputeall', 'Position', ppo, ...
    'Callback', 'DataManager_BehavReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'EventLocations', 'Units', 'normalized', 'Tag', 'eventlocations', 'Position', ppo, ...
    'Callback', 'DataManager_BehavEventTriggers_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'EventTrigedAvgs', 'Units', 'normalized', 'Tag', 'eventtrigbehavparm', 'Position', ppo, ...
    'Callback', 'DataManager_BehavEventTriggers_Callback');
%%%%additonal plots to show hidden bhdata 
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3.35*Vgap-3.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'showData', 'Units', 'normalized', 'Tag', 'showposdata', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-5.35*Vgap-5.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evLinearX', 'Units', 'normalized', 'Tag', 'evlinearx', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-5.35*Vgap-5.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evLinearY', 'Units', 'normalized', 'Tag', 'evlineary', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-6.35*Vgap-6.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evVel/1dSpeed', 'Units', 'normalized', 'Tag', 'evvel', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-6.35*Vgap-6.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evHeaddir', 'Units', 'normalized', 'Tag', 'evheaddir', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'sessTraj', 'Units', 'normalized', 'Tag', 'sesstraj', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evTraj', 'Units', 'normalized', 'Tag', 'evtraj', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'sessOccupcy', 'Units', 'normalized', 'Tag', 'sessoccup', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evOccupcy', 'Units', 'normalized', 'Tag', 'evoccup', 'Position', ppo, ...
    'Callback', 'DataManager_BehavShowBhdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);

function plotcrrdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth)
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptInit', 'Units', 'normalized', 'Tag', 'recomputeinit', 'Position', ppo, ...
    'Callback', 'DataManager_CrrReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptAll', 'Units', 'normalized', 'Tag', 'recomputeall', 'Position', ppo, ...
    'Callback', 'DataManager_CrrReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'CrossCrr', 'Units', 'normalized', 'Tag', 'crosscrr', 'Position', ppo, ...
    'Callback', 'DataManager_CrrReCompute_Callback');
ppo = [pp(1)+3*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'TransferCellVariables', 'Units', 'normalized', 'Tag', 'transfercellvariables', 'Position', ppo, ...
    'Callback', 'DataManager_CrrReCompute_Callback');

%ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
%     'String', 'CrossCrr', 'Units', 'normalized', 'Tag', 'crosscrr', 'Position', ppo, ...
%     'Callback', 'DataManager_CrrReCompute_Callback');
%%%%additonal plots to show hidden bhdata 
ppo = [pp(1)+Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'sessCrossCrr', 'Units', 'normalized', 'Tag', 'showsessioncrr', 'Position', ppo, ...
    'Callback', 'DataManager_ShowCrrdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evCrossCrr', 'Units', 'normalized', 'Tag', 'showevcrr', 'Position', ppo, ...
    'Callback', 'DataManager_ShowCrrdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'sessAvgCCrr', 'Units', 'normalized', 'Tag', 'showsessaveragecrr', 'Position', ppo, ...
    'Callback', 'DataManager_ShowCrrdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth/2 Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evAvgCC', 'Units', 'normalized', 'Tag', 'showevaveragecrr', 'Position', ppo, ...
    'Callback', 'DataManager_ShowCrrdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth*3/2+4*Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth/2 Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evCCcolor', 'Units', 'normalized', 'Tag', 'showevcrrcolor', 'Position', ppo, ...
    'Callback', 'DataManager_ShowCrrdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);

function plotsyncdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth)
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptInit', 'Units', 'normalized', 'Tag', 'recomputeinit', 'Position', ppo, ...
    'Callback', 'DataManager_SyncReCompute_Callback');
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ReCmptAll', 'Units', 'normalized', 'Tag', 'recomputeall', 'Position', ppo, ...
    'Callback', 'DataManager_SyncReCompute_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'Sync', 'Units', 'normalized', 'Tag', 'sync', 'Position', ppo, ...
    'Callback', 'DataManager_SyncReCompute_Callback');
%ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
%     'String', 'CrossCrr', 'Units', 'normalized', 'Tag', 'crosscrr', 'Position', ppo, ...
%     'Callback', 'DataManager_CrrReCompute_Callback');
%%%%additonal plots to show hidden bhdata 
ppo = [pp(1)+Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'sessSync', 'Units', 'normalized', 'Tag', 'showsessionsync', 'Position', ppo, ...
    'Callback', 'DataManager_ShowSyncdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-7.35*Vgap-7.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evSync', 'Units', 'normalized', 'Tag', 'showevsync', 'Position', ppo, ...
    'Callback', 'DataManager_ShowSyncdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'sessAvgSync', 'Units', 'normalized', 'Tag', 'showsessaveragesync', 'Position', ppo, ...
    'Callback', 'DataManager_ShowSyncdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);
ppo = [pp(1)+Bwidth+3*Hgap  pp(2)+pp(4)-8.35*Vgap-8.35*Bheight Bwidth Bheight]; ppt= uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'evAvgSync', 'Units', 'normalized', 'Tag', 'showevaveragesync', 'Position', ppo, ...
    'Callback', 'DataManager_ShowSyncdata_Callback'); set(ppt, 'ForeGroundColor', [0.2 0.2 0.2]);

function plotseqdbcontrols(hf, pp, Hgap, Vgap, Bheight, Bwidth, plotparm)
%%%%%%%%%%%significance parameters
% ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight 2*Bwidth Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
%     'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'Significance Parameters',...
%     'Units', 'normalized', 'Tag', 'shufflestatic', 'Position',ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
%     'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'SignfcanceLevel',...
%     'Units', 'normalized', 'Tag', 'shufflestatic', 'Position',ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+Hgap+Bwidth  pp(2)+pp(4)-3*Vgap-3*Bheight Bwidth Bheight+Vgap]; uicontrol('Style', 'edit', 'Parent', hf,...
%     'ForegroundColor', [1 0 0], 'String', plotparm.significancelevel,...
%     'Units', 'normalized', 'Tag', 'setsignificancelevel', 'Position', ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
%     'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'ShuffleMode',...
%     'Units', 'normalized', 'Tag', 'shufflestatic', 'Position',ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+Hgap+Bwidth  pp(2)+pp(4)-4*Vgap-4*Bheight Bwidth Bheight+Vgap]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
%     'ForegroundColor', [1 0 0], 'String', plotparm.shufflemode,...
%     'Units', 'normalized', 'Tag', 'setshufflemode', 'Position', ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+3*Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
%     'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'ShuffleTimes',...
%     'Units', 'normalized', 'Tag', 'shufflestatic', 'Position',ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+3*Hgap+Bwidth  pp(2)+pp(4)-5*Vgap-5*Bheight Bwidth Bheight-Vgap]; uicontrol('Style', 'edit', 'Parent', hf,...
%     'ForegroundColor', [1 0 0], 'String', num2str(plotparm.shuffletimes),...
%     'Units', 'normalized', 'Tag', 'setshuffletimes', 'Position', ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+Hgap  pp(2)+pp(4)-6*Vgap-6*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
%     'String', 'ShowSequences', 'Units', 'normalized', 'Tag', 'showshufflecopy', 'Position', ppo, ...
%     'Callback', 'DM_Seq_ShowSequences_Callback');
% ppo = [pp(1)+Hgap  pp(2)+pp(4)-7*Vgap-7*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
%     'String', 'ShowShuffleSignificance', 'Units', 'normalized', 'Tag', 'showshufflesignificance', 'Position', ppo, ...
%     'Callback', 'DM_Seq_PlotSignificance_Callback');
% ppo = [pp(1)+Hgap  pp(2)+pp(4)-8*Vgap-8*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
%     'String', 'ShowComputedSignificance', 'Units', 'normalized', 'Tag', 'showtheoreticalsignificance', 'Position', ppo, ...
%     'Callback', 'DM_Seq_PlotSignificance_Callback');
% % ppo = [pp(1)+Hgap  pp(2)+pp(4)-9*Vgap-9*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
% %     'String', 'ShowSequenceLocations', 'Units', 'normalized', 'Tag', 'showsequencelocations', 'Position', ppo, ...
% %     'Callback', 'DM_Seq_ShowSequenceLocations_Callback');
% ppo = [pp(1)+3*Hgap+Bwidth  pp(2)+pp(4)-9*Vgap-9*Bheight Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
%    'String', 'EventItemized', 'Units', 'normalized', 'Tag', 'eventitemized', 'Position', ppo, ...
%    'Callback', 'DM_Seq_EventItemized_Callback');

ppo = [pp(1)+Hgap  pp(2)+pp(4)-1*Vgap-1*Bheight 2*Bwidth Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
    'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'For selected 1 template:',...
    'Units', 'normalized', 'Tag', 'shufflestatic', 'Position',ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-2*Vgap-2*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ShowSequences', 'Units', 'normalized', 'Tag', 'showsequences', 'Position', ppo, ...
    'Callback', 'DM_Seq_ShowSequences_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-3*Vgap-3*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ShowASuffledCopy', 'Units', 'normalized', 'Tag', 'showshufflecopy', 'Position', ppo, ...
    'Callback', 'DM_Seq_ShowSequences_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-4*Vgap-4*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'ShowSequenceLocations', 'Units', 'normalized', 'Tag', 'showsequencelocations', 'Position', ppo, ...
    'Callback', 'DM_Seq_ShowSequenceLocations_Callback');

ppo = [pp(1)+Hgap  pp(2)+pp(4)-5*Vgap-5*Bheight 2*Bwidth Bheight-Vgap]; uicontrol('Style', 'text', 'Parent', hf,...
    'ForegroundColor', [0 0 1], 'BackgroundColor', [0.8 0.8 0.8], 'String', 'For selected templates:',...
    'Units', 'normalized', 'Tag', 'shufflestatic', 'Position',ppo, 'Callback', 'DM_Seq_PlotSignificance_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-6*Vgap-6*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'PlotCombinedShufSignificance', 'Units', 'normalized', 'Tag', 'showshufflesignificance', 'Position', ppo, ...
    'Callback', 'DM_Seq_PlotSignificance_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-7*Vgap-7*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'CompareHiddenQuantities', 'Units', 'normalized', 'Tag', 'comparevartoshuffles', 'Position', ppo, ...
    'Callback', 'DM_Seq_CompareVariables_Callback');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-8*Vgap-8*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
    'String', 'QuantifySequenceLocations', 'Units', 'normalized', 'Tag', 'comparevartoshuffles', 'Position', ppo, ...
    'Callback', 'DM_Seq_PlotSequenceLocation');
ppo = [pp(1)+Hgap  pp(2)+pp(4)-9*Vgap-9*Bheight 2*Bwidth Bheight]; uicontrol('Style', 'pushbutton', 'Parent', hf,...
   'String', 'Recompute - EventItemized', 'Units', 'normalized', 'Tag', 'eventitemized', 'Position', ppo, ...
   'Callback', 'DM_Seq_EventItemized_Callback');




